from .Model import Model
from .TransE import TransE
from .TransH import TransH
from .TransD import TransD
from .TransD import TransD
from .TransR import TransR
from .RESCAL import RESCAL
from .DistMult import DistMult
from .HolE import HolE
from .ComplEx import ComplEx
from .Analogy import Analogy
