from . import Model
from Model import *
from . import TransE
from TransE import *
from . import TransH
from TransH import *
from . import TransD
from TransD import *
from . import TransR
from TransR import *
from . import RESCAL
from RESCAL import *
from . import DistMult
from DistMult import *
from . import HolE
from HolE import *
from . import ComplEx
from ComplEx import *
