from .Model import Model
from .TransE import TransE
from .TransD import TransD
from .TransR import TransR
from .TransH import TransH
from .DistMult import DistMult
from .ComplEx import ComplEx
from .RESCAL import RESCAL
from .Analogy import Analogy
from .SimplE import SimplE
from .RotatE import RotatE